[package]
name = "edgefirst-model"
description = "EdgeFirst Model Node - AI inference service for EdgeFirst Perception"
repository = "https://github.com/EdgeFirstAI/model"
homepage = "https://www.edgefirst.ai"
license = "Apache-2.0"
version = "2.10.1"
edition = "2024"

[profile.release]
opt-level = 3
lto = true
strip = true
debug = false

[profile.profiling]
inherits = "release"
strip = false
debug = true
lto = false

[features]
default = ["tracy"]
tracy = ["tracing-tracy/enable", "tracy-client/enable"]
profiling = [
    "tracing-tracy/sampling",
    "tracing-tracy/system-tracing",
    "tracy-client/sampling",
    "tracy-client/system-tracing",
]

[dependencies]
ara2 = "0.16"
async-pidfd = "0.1.4"
clap = { version = "4.6.6", features = ["derive", "env"] }
edgefirst-hal = "0.28"
edgefirst-tflite = { version = "0.7", features = ["full"] }
edgefirst-schemas = "4.0.0"
edgefirst-tracker = "0.28"
log = { version = "0.4.28" }
ndarray = { version = "0.17", features = ["rayon"] }
nix = { version = "0.30.1", features = ["time"] }
pidfd_getfd = "0.2.2"
serde_json = "1.0.142"
tokio = { version = "1.53.1", features = [
    "rt-multi-thread",
    "time",
    "io-std",
    "tracing",
] }
tracing = "0.1.44"
tracing-journald = "0.3.2"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.23"
tracing-tracy = { version = "0.12.0", default-features = false, features = [
    "manual-lifetime",
    "broadcast",
    "ondemand",
    "fibers",
] }
tracy-client = { version = "0.19.0", default-features = false, features = [
    "manual-lifetime",
    "broadcast",
    "ondemand",
    "fibers",
] }
zip = "5.0.0"
zenoh = "1.10.0"
libc = "0.2"
gethostname = "1.1.0"

[dev-dependencies]
edgefirst-schemas = "4.0.0"
image = "0.25"
libc = "0.2"
zenoh = "1.10.0"
